### ISSUE TITLE
Agree Rover v2 Symphony YAML spec

### ISSUE THREAD

**Issue by benc-uk** [aztfmod/rovergo#36]
Current working draft

```yaml
symphonyVersion: 2

# The CAF environment name
environment: benc

# The path to the CAF landingzones repo
landingZonePath: /home/ben/proj/aztfmod/landingzones

# It is critical that this matches the container names in launchpad storage_accounts.tfvars
workspace: tfstate

levels:
  - level: 0
    launchpad: true
    stacks:
      - stack: lp
        configurationPath: ./local/configs/level0/launchpad
  - level: 1
    stacks:
      - stack: web
        configurationPath: ./local/configs/level1/web
      - stack: test
        configurationPath: ./local/configs/level1/test
```
